# Generated by Django 5.1.2 on 2024-10-28 11:07

import django_extensions.db.fields
import feedback.models
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField()),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('page_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=feedback.models.screenshot_upload_to)),
                ('screenshot_size', models.PositiveIntegerField(blank=True, null=True)),
                ('blackbox', models.FileField(blank=True, null=True, upload_to=feedback.models.blackbox_upload_to)),
                ('blackbox_size', models.PositiveIntegerField(blank=True, null=True)),
                ('system_logs', models.FileField(blank=True, null=True, upload_to=feedback.models.logs_upload_to)),
                ('system_logs_size', models.PositiveIntegerField(blank=True, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to=feedback.models.attach_upload_to)),
                ('attached_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback_data', jsonfield.fields.JSONField(blank=True, help_text='JSON format', null=True, verbose_name='Feedback data')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackDescription',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feedback.feedback',),
        ),
    ]
