# Generated by Django 5.1.2 on 2024-10-28 11:07

import crash.models
import django.core.files.storage
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('upload_file_minidump', models.FileField(blank=True, max_length=255, null=True, upload_to=crash.models.crash_upload_to)),
                ('minidump_size', models.PositiveIntegerField(blank=True, null=True)),
                ('archive', models.FileField(blank=True, max_length=255, null=True, upload_to=crash.models.crash_archive_upload_to)),
                ('archive_size', models.PositiveIntegerField(blank=True, null=True)),
                ('appid', models.CharField(blank=True, max_length=38, null=True)),
                ('userid', models.CharField(blank=True, max_length=38, null=True)),
                ('meta', jsonfield.fields.JSONField(blank=True, help_text='JSON format', null=True, verbose_name='Meta-information')),
                ('stacktrace', models.TextField(blank=True, null=True)),
                ('stacktrace_json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('groupid', models.CharField(blank=True, max_length=38, null=True)),
                ('eventid', models.CharField(blank=True, max_length=38, null=True)),
                ('os', models.CharField(blank=True, max_length=32, null=True)),
                ('build_number', models.CharField(blank=True, max_length=32, null=True)),
                ('channel', models.CharField(blank=True, default='', max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'Crashes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrashDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('crash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crash_description', to='crash.crash')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('debug_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Debug ID')),
                ('debug_file', models.CharField(blank=True, max_length=140, null=True, verbose_name='Debug file name')),
                ('file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=crash.models.symbols_upload_to)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Symbols',
                'unique_together': {('debug_id', 'debug_file')},
            },
        ),
    ]
