# Generated by Django 5.1.2 on 2024-10-30 13:14

import omaha.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=omaha.models._version_upload_to),
        ),
    ]
