# Generated by Django 5.1.2 on 2024-11-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0002_alter_version_file'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE versions ALTER COLUMN version TYPE BIGINT;',
            reverse_sql='ALTER TABLE versions ALTER COLUMN version TYPE INTEGER;',
        ),
    ]
