version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgre
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=passpostgre

  redis:
    restart: always
    image: redis:5
    ports:
      - "6379:6379"



volumes:
  postgres_data:
  static_volume:
  media_volume:

