# Generated by Django 5.1.2 on 2024-10-28 07:38

import django.core.files.storage
import django.db.models.deletion
import django_extensions.db.fields
import sparkle.models
import versionfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('omaha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparkleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('version', versionfield.fields.VersionField(db_index=True, help_text='Format: 65535.65535')),
                ('short_version', versionfield.fields.VersionField(blank=True, help_text='Format: 255.255.65535.65535', null=True)),
                ('minimum_system_version', versionfield.fields.VersionField(blank=True, help_text='Format: 255.255.255', null=True)),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=sparkle.models._version_upload_to)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('dsa_signature', models.CharField(blank=True, max_length=140, null=True, verbose_name='DSA signature')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omaha.application')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omaha.channel')),
            ],
            options={
                'indexes': [models.Index(fields=['app', 'channel'], name='sparkle_spa_app_id_b7ef55_idx')],
                'unique_together': {('app', 'channel', 'version')},
            },
        ),
    ]
